import type { FAQ } from '@/lib/schema'

export interface Profissao {
  slug: string
  name: string
  /** e.g. "para Pedreiro", "para Diarista" */
  prepoLabel: string
  /** tool to link as primary CTA */
  toolHref: string
  toolLabel: string
  /** 2-sentence intro explaining when this profession uses receipts */
  intro: string
  /** When to issue a receipt */
  quando: string[]
  /** Required fields on the receipt for this profession */
  campos: string[]
  faqs: FAQ[]
  /** Related profissao slugs */
  related: string[]
  /** Primary keyword (for meta title) */
  keyword: string
  metaDescription: string
}

const profissoes: Profissao[] = [
  {
    slug: 'pedreiro',
    name: 'Pedreiro',
    prepoLabel: 'para Pedreiro',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Pedreiro',
    keyword: 'recibo para pedreiro',
    metaDescription: 'Modelo gratuito de recibo para pedreiro. Comprove o pagamento por serviços de alvenaria, construção e reforma. Gere em PDF sem cadastro.',
    intro: 'O pedreiro autônomo precisa emitir recibo para cada serviço de alvenaria, reboco, assentamento ou reforma concluído. O recibo protege tanto o pedreiro quanto o contratante e serve como comprovante de quitação.',
    quando: ['Ao finalizar uma obra ou etapa de construção', 'Após receber pagamento por empreitada', 'Ao receber sinal ou parcela de serviço', 'Para regularizar pagamentos informais anteriores'],
    campos: ['Nome completo e CPF do pedreiro', 'Nome e CPF/CNPJ de quem contratou', 'Descrição do serviço: tipo de obra, metragem, local', 'Valor recebido (número e por extenso)', 'Forma de pagamento (dinheiro, PIX, transferência)', 'Data do recebimento', 'Assinatura do pedreiro'],
    faqs: [
      { q: 'Pedreiro autônomo precisa de nota fiscal?', a: 'Para serviços a pessoas físicas, o recibo simples é suficiente. Para empresas (CNPJ), o correto é emitir RPA (Recibo de Pagamento de Autônomo) ou, se tiver MEI, nota fiscal de serviços.' },
      { q: 'Recibo de pedreiro vale como contrato?', a: 'Não. O recibo comprova o pagamento recebido. Para garantir o escopo, prazo e valor do serviço, use um contrato de prestação de serviços separado.' },
      { q: 'O pedreiro paga imposto sobre o recibo?', a: 'Como autônomo, o pedreiro está sujeito ao Carnê-Leão (IRPF) sobre os rendimentos recebidos de pessoas físicas. Acima do limite de isenção anual, deve declarar no IRPF.' },
    ],
    related: ['encanador', 'pintor', 'eletricista'],
  },
  {
    slug: 'diarista',
    name: 'Diarista',
    prepoLabel: 'para Diarista',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Diarista',
    keyword: 'recibo para diarista',
    metaDescription: 'Modelo gratuito de recibo para diarista. Comprove o pagamento por dia de serviço. Gere em PDF sem cadastro. Válido juridicamente.',
    intro: 'A diarista que trabalha por conta própria (sem registro em carteira) deve emitir recibo a cada pagamento. O documento protege a diarista e o contratante e pode ser usado como comprovante de renda.',
    quando: ['A cada diária trabalhada', 'Ao receber pagamento mensal por diarista frequente', 'Para comprovar renda em financiamentos e aluguéis', 'Quando o contratante solicitar comprovante'],
    campos: ['Nome completo e CPF da diarista', 'Nome e CPF do contratante', 'Número de diárias ou período trabalhado', 'Valor por diária e total recebido', 'Endereço do local de trabalho (opcional)', 'Data do recebimento', 'Assinatura da diarista'],
    faqs: [
      { q: 'Diarista precisa assinar carteira?', a: 'Diarista que trabalha em até 2 dias por semana para o mesmo empregador é considerada autônoma (não precisa de registro). Acima de 2 dias por semana para o mesmo empregador, deve ter carteira assinada.' },
      { q: 'Recibo de diarista serve como comprovante de renda?', a: 'Sim. O recibo pode ser usado para comprovar renda em bancos, financeiras e financiamentos. Para aprovação de crédito, some 3 a 6 meses de recibos para mostrar histórico de renda.' },
      { q: 'Diarista MEI pode emitir recibo?', a: 'Diaristas geralmente não podem ser MEI, pois a atividade não está na lista de ocupações permitidas pelo MEI. Como autônoma, emite recibo simples.' },
    ],
    related: ['faxineiro', 'cuidador-de-idosos', 'baba'],
  },
  {
    slug: 'autonomo',
    name: 'Autônomo',
    prepoLabel: 'para Autônomo',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Autônomo',
    keyword: 'recibo para autonomo',
    metaDescription: 'Modelo gratuito de recibo para autônomo. Para serviços a pessoas físicas use recibo simples; para empresas, use RPA. Gere em PDF grátis.',
    intro: 'O trabalhador autônomo usa o recibo para comprovar o recebimento de pagamentos por serviços prestados. Dependendo de quem contratou, o tipo de documento correto varia.',
    quando: ['Serviços prestados a pessoas físicas (CPF)', 'Quando o contratante pede comprovante escrito', 'Para registrar pagamentos parcelados', 'Para comprovar renda'],
    campos: ['Nome, CPF e endereço do autônomo', 'Nome e CPF/CNPJ do contratante', 'Descrição detalhada do serviço prestado', 'Valor recebido (número e por extenso)', 'Data do recebimento', 'Assinatura do autônomo'],
    faqs: [
      { q: 'Quando usar recibo e quando usar RPA?', a: 'Use recibo simples para serviços a pessoas físicas. Use o RPA (Recibo de Pagamento de Autônomo) para serviços a empresas — nele a empresa desconta INSS, IR e ISS antes de pagar.' },
      { q: 'Autônomo precisa declarar IR?', a: 'Sim. Rendimentos de autônomo devem ser declarados anualmente no IRPF. Se receber de pessoas físicas, paga Carnê-Leão mensalmente.' },
      { q: 'Recibo de autônomo tem prazo de validade?', a: 'Não há prazo de validade. O recibo é permanentemente válido como comprovante do pagamento realizado na data indicada. Guarde por pelo menos 5 anos.' },
    ],
    related: ['freelancer', 'consultor', 'programador'],
  },
  {
    slug: 'freelancer',
    name: 'Freelancer',
    prepoLabel: 'para Freelancer',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Freelancer',
    keyword: 'recibo para freelancer',
    metaDescription: 'Modelo gratuito de recibo para freelancer. Comprove pagamentos por projetos, designs, textos e programação. Gere em PDF sem cadastro.',
    intro: 'Freelancers de qualquer área precisam emitir recibo ao final de cada projeto ou ao receber pagamentos. O documento formaliza a relação comercial e serve como prova de pagamento.',
    quando: ['Ao receber pagamento por projeto concluído', 'Em pagamentos parciais (sinal + final)', 'Para clientes pessoa física que pedem comprovante', 'Para construir histórico de renda'],
    campos: ['Nome, CPF e área de atuação', 'Nome e CPF/CNPJ do cliente', 'Descrição do projeto/serviço entregue', 'Valor total recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Freelancer sem CNPJ pode emitir recibo?', a: 'Sim. Qualquer pessoa física pode emitir recibo de prestação de serviço sem precisar de CNPJ. Para clientes empresas, o ideal é o RPA.' },
      { q: 'Qual a diferença entre recibo e contrato para freelancer?', a: 'O contrato define o que será feito, prazo, valor e condições. O recibo comprova o pagamento. Você precisa dos dois: contrato antes do serviço, recibo depois do pagamento.' },
      { q: 'Freelancer deve emitir nota fiscal?', a: 'Para pessoas físicas, o recibo basta. Para empresas, o ideal é ter MEI e emitir nota fiscal de serviços. Sem MEI, use o RPA.' },
    ],
    related: ['programador', 'designer', 'consultor'],
  },
  {
    slug: 'motorista',
    name: 'Motorista',
    prepoLabel: 'para Motorista',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Motorista',
    keyword: 'recibo para motorista',
    metaDescription: 'Modelo gratuito de recibo para motorista autônomo. Para fretes, transporte escolar, motorista particular e serviços de entrega. Gere em PDF.',
    intro: 'Motoristas autônomos que prestam serviços de transporte, frete ou entrega precisam emitir recibo ao ser pagos. O documento registra o serviço realizado e o valor recebido.',
    quando: ['Após realizar frete ou entrega', 'Ao receber pagamento mensal de transporte escolar', 'Por serviços de motorista particular ou executivo', 'Para corridas ou serviços avulsos'],
    campos: ['Nome e CPF do motorista', 'Nome e CPF/CNPJ do contratante', 'Descrição do serviço: tipo de transporte, origem e destino', 'Valor do frete ou do serviço', 'Data do serviço e do recebimento', 'Assinatura do motorista'],
    faqs: [
      { q: 'Motorista de aplicativo precisa emitir recibo?', a: 'O próprio aplicativo (Uber, 99, etc.) gera o comprovante da corrida. Para serviços avulsos fora do app, emita recibo.' },
      { q: 'Transportador autônomo precisa de nota fiscal?', a: 'Para transporte de carga a empresas, geralmente é exigido CT-e (Conhecimento de Transporte) ou nota fiscal. Para serviços a pessoas físicas, o recibo é suficiente.' },
      { q: 'Recibo de frete tem valor legal?', a: 'Sim. O recibo de frete é um documento válido que comprova a prestação do serviço e o pagamento recebido. Guarde-o por pelo menos 5 anos.' },
    ],
    related: ['autonomo', 'freelancer', 'consultor'],
  },
  {
    slug: 'professor',
    name: 'Professor',
    prepoLabel: 'para Professor',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Professor',
    keyword: 'recibo para professor',
    metaDescription: 'Modelo gratuito de recibo para professor particular. Para aulas avulsas, cursos e reforço escolar. Gere em PDF sem cadastro.',
    intro: 'Professores particulares e tutores que dão aulas avulsas ou reforço escolar precisam emitir recibo para cada pagamento. O documento formaliza o serviço de educação prestado.',
    quando: ['Ao receber pagamento por aulas particulares', 'Para reforço escolar e tutoria', 'Por cursos ou workshops ministrados', 'Para pacotes mensais de aulas'],
    campos: ['Nome e CPF do professor', 'Nome e CPF do aluno ou responsável', 'Descrição: disciplina, número de aulas ou período', 'Valor recebido', 'Data do recebimento', 'Assinatura do professor'],
    faqs: [
      { q: 'Professor particular precisa de CNPJ?', a: 'Não obrigatoriamente. Como autônomo, o professor pode emitir recibos simples para alunos pessoa física. Se quiser MEI, há restrições — professores particulares geralmente não se enquadram como MEI.' },
      { q: 'Recibo de aula particular vale para imposto de renda?', a: 'O recibo registra o rendimento que deve ser declarado no IRPF. Pais que pagam aulas podem usar o recibo para deduzir despesas de educação dentro dos limites legais.' },
      { q: 'Professor pode cobrar por PIX e emitir recibo?', a: 'Sim. O meio de pagamento (PIX, dinheiro, transferência) não altera a necessidade de emitir recibo. O recibo especifica o que foi pago e formaliza o serviço.' },
    ],
    related: ['autonomo', 'freelancer', 'consultor'],
  },
  {
    slug: 'programador',
    name: 'Programador',
    prepoLabel: 'para Programador',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Programador',
    keyword: 'recibo para programador',
    metaDescription: 'Modelo gratuito de recibo para programador freelancer. Para desenvolvimento de sistemas, sites, apps e consultoria de TI. Gere em PDF.',
    intro: 'Programadores freelancers que desenvolvem sistemas, sites ou apps para clientes precisam formalizar cada pagamento com um recibo. O documento registra o projeto entregue e o valor pago.',
    quando: ['Ao receber pagamento por desenvolvimento de projeto', 'Por consultoria e assessoria técnica', 'Para manutenção e suporte de sistemas', 'Por licenciamento ou entrega de código'],
    campos: ['Nome, CPF e especialidade do programador', 'Nome e CPF/CNPJ do cliente', 'Descrição: tipo de sistema, tecnologias, entregável', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Programador deve ter MEI?', a: 'Desenvolvimento de software está na lista de atividades permitidas para MEI desde 2023. Com MEI, o programador emite nota fiscal de serviços para empresas — mais prático que o RPA.' },
      { q: 'Como cobrar por projetos de programação?', a: 'Opções: por hora (registre as horas em contrato), por projeto (valor fechado com escopo definido), ou por retainer (mensalidade). Em todos os casos, emita recibo ou nota fiscal.' },
      { q: 'Recibo de programador protege contra "não recebi o que pedi"?', a: 'O recibo comprova apenas o pagamento. Para proteger contra disputas sobre o que foi entregue, use um contrato detalhado com escopo, prazo e definição de aceite.' },
    ],
    related: ['freelancer', 'designer', 'consultor'],
  },
  {
    slug: 'consultor',
    name: 'Consultor',
    prepoLabel: 'para Consultor',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Consultor',
    keyword: 'recibo para consultor',
    metaDescription: 'Modelo gratuito de recibo para consultor autônomo. Para consultoria de negócios, TI, RH, financeira e estratégica. Gere em PDF sem cadastro.',
    intro: 'Consultores autônomos de qualquer área devem emitir recibo ao receber honorários por seus serviços. O documento garante transparência e serve como prova de pagamento.',
    quando: ['Ao receber honorários de consultoria', 'Por projetos estratégicos ou diagnósticos', 'Por reuniões ou workshops de consultoria', 'Para contratos de assessoria continuada'],
    campos: ['Nome, CPF e área de consultoria', 'Nome e CPF/CNPJ do cliente', 'Descrição: escopo da consultoria, período', 'Honorários recebidos', 'Data do recebimento', 'Assinatura do consultor'],
    faqs: [
      { q: 'Consultor deve ter empresa (CNPJ) para prestar serviços?', a: 'Não é obrigatório. Como pessoa física (autônomo), o consultor emite RPA para empresas ou recibo simples para pessoas físicas. Ter CNPJ (PJ) pode ser vantajoso para impostos e credibilidade.' },
      { q: 'Como precificar consultoria?', a: 'Consultores cobram por hora, por projeto, ou por retainer mensal. A precificação depende da especialidade, experiência e mercado. Documente sempre o valor acordado em contrato.' },
      { q: 'Recibo de consultoria pode ser emitido em nome da empresa?', a: 'Se você tem CNPJ, emita nota fiscal em nome da empresa. O recibo é para autônomos pessoa física.' },
    ],
    related: ['autonomo', 'freelancer', 'programador'],
  },
  {
    slug: 'encanador',
    name: 'Encanador',
    prepoLabel: 'para Encanador',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Encanador',
    keyword: 'recibo para encanador',
    metaDescription: 'Modelo gratuito de recibo para encanador autônomo. Para serviços de hidráulica, reparos e instalações. Gere em PDF sem cadastro.',
    intro: 'O encanador autônomo deve emitir recibo após cada serviço concluído e pago. O documento registra o trabalho realizado e protege o profissional em caso de disputas.',
    quando: ['Após reparo ou instalação hidráulica', 'Ao receber pagamento por empreitada', 'Para serviços em condomínios ou empresas', 'Ao receber sinal ou parcela'],
    campos: ['Nome e CPF do encanador', 'Nome e CPF/CNPJ do contratante', 'Descrição: tipo de serviço hidráulico e local', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Encanador pode ser MEI?', a: 'Sim. O encanador pode ser MEI (Instalador Hidráulico - CNAE 4329-1/01). Como MEI, emite nota fiscal para empresas e pode ter cartão CNPJ.' },
      { q: 'Recibo de encanador precisa descrever o serviço?', a: 'Sim. Descreva o serviço realizado (ex: "troca de sifão e cano de esgoto no banheiro da cozinha"). Uma descrição clara evita conflitos sobre o que foi executado.' },
      { q: 'E se o cliente reclamar do serviço após pagar?', a: 'Com o recibo, fica documentado que o pagamento foi feito. Para garantias de serviço, inclua no recibo ou contrato o prazo de garantia do trabalho realizado.' },
    ],
    related: ['pedreiro', 'eletricista', 'pintor'],
  },
  {
    slug: 'eletricista',
    name: 'Eletricista',
    prepoLabel: 'para Eletricista',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Eletricista',
    keyword: 'recibo para eletricista',
    metaDescription: 'Modelo gratuito de recibo para eletricista autônomo. Para instalações elétricas, reparos e laudos. Gere em PDF sem cadastro.',
    intro: 'Eletricistas autônomos devem emitir recibo por cada serviço de instalação ou reparo elétrico. O documento é o comprovante do trabalho realizado e do valor cobrado.',
    quando: ['Após instalação ou reparo elétrico', 'Para serviços em residências e comércios', 'Ao receber por laudo ou SPDA', 'Para contratos de manutenção periódica'],
    campos: ['Nome e CPF/CREA do eletricista', 'Nome e CPF/CNPJ do contratante', 'Descrição: tipo de serviço elétrico e endereço', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Eletricista precisa de registro no CREA?', a: 'Para serviços que exigem ART (instalações de médio e grande porte), sim. Para reparos residenciais simples, a obrigatoriedade varia por estado e município.' },
      { q: 'Eletricista MEI pode trabalhar para empresas?', a: 'Sim. Eletricista pode ser MEI (Eletricista - CNAE 4321-5/00). Como MEI, emite nota fiscal para empresas contratantes.' },
      { q: 'Recibo de eletricista serve como garantia do serviço?', a: 'Não automaticamente. Para garantias de serviço, inclua no recibo ou contrato o prazo de garantia (ex: "90 dias de garantia para a instalação realizada").' },
    ],
    related: ['pedreiro', 'encanador', 'pintor'],
  },
  {
    slug: 'pintor',
    name: 'Pintor',
    prepoLabel: 'para Pintor',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Pintor',
    keyword: 'recibo para pintor',
    metaDescription: 'Modelo gratuito de recibo para pintor autônomo. Para pintura residencial, comercial e reforma. Gere em PDF sem cadastro.',
    intro: 'Pintores autônomos devem emitir recibo ao serem pagos por serviços de pintura residencial ou comercial. O documento formaliza o pagamento e serve como prova de quitação.',
    quando: ['Ao finalizar uma obra de pintura', 'Para pintura por cômodo ou metragem', 'Ao receber sinal ou parcela', 'Para serviços de massa e textura'],
    campos: ['Nome e CPF do pintor', 'Nome e CPF/CNPJ do contratante', 'Descrição: tipo de pintura, local e metragem aproximada', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Pintor pode ser MEI?', a: 'Sim. Pintor pode se registrar como MEI (Pintor de imóveis - CNAE 4330-4/04). Como MEI, emite nota fiscal e tem acesso a crédito no CNPJ.' },
      { q: 'Como cobrar pintura: por metro ou por serviço?', a: 'Ambos são válidos. Por metro quadrado é mais transparente para o cliente. Por empreitada (valor total) é mais simples. Em qualquer caso, documente no recibo o que foi cobrado.' },
      { q: 'O que fazer se o cliente não pagar após o serviço?', a: 'Com recibo ou contrato assinado, você pode recorrer ao Juizado Especial Cível (JEC/Pequenas Causas) para valores até 40 salários mínimos, sem precisar de advogado.' },
    ],
    related: ['pedreiro', 'encanador', 'eletricista'],
  },
  {
    slug: 'designer',
    name: 'Designer',
    prepoLabel: 'para Designer',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Designer',
    keyword: 'recibo para designer',
    metaDescription: 'Modelo gratuito de recibo para designer freelancer. Para identidade visual, web design, ilustração e UI/UX. Gere em PDF sem cadastro.',
    intro: 'Designers freelancers devem emitir recibo ao receber pagamento por projetos criativos. O documento protege o designer e o cliente, formalizando a entrega e o pagamento.',
    quando: ['Ao receber por identidade visual ou logo', 'Para projetos de web design ou UI/UX', 'Por criação de materiais gráficos', 'Para contratos de design contínuo'],
    campos: ['Nome, CPF e especialidade do designer', 'Nome e CPF/CNPJ do cliente', 'Descrição: projeto, entregáveis (arquivos, formatos)', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Designer precisa ceder os direitos autorais no recibo?', a: 'O recibo comprova o pagamento, não a cessão de direitos. A cessão de direitos deve ser tratada no contrato separadamente, especificando quais usos o cliente pode fazer.' },
      { q: 'Designer freelancer: MEI ou PJ?', a: 'Design gráfico está na lista MEI. Designer com faturamento até R$ 81.000/ano pode ser MEI. Acima disso, abre Simples Nacional ou Lucro Presumido.' },
      { q: 'O que fazer se o cliente usar o material sem pagar?', a: 'Documente tudo: briefing, rascunhos, entregas por e-mail e o recibo/contrato. Ações por direito autoral ou cobrança de honorários podem ser movidas no JEC.' },
    ],
    related: ['programador', 'freelancer', 'fotografo'],
  },
  {
    slug: 'fotografo',
    name: 'Fotógrafo',
    prepoLabel: 'para Fotógrafo',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Fotógrafo',
    keyword: 'recibo para fotografo',
    metaDescription: 'Modelo gratuito de recibo para fotógrafo freelancer. Para ensaios, eventos, casamentos e fotografia comercial. Gere em PDF sem cadastro.',
    intro: 'Fotógrafos profissionais que trabalham como freelancers precisam emitir recibo por cada trabalho realizado. O documento formaliza o pagamento e garante segurança para ambas as partes.',
    quando: ['Ao receber por ensaio fotográfico', 'Após cobertura de evento ou casamento', 'Por trabalhos para publicidade e e-commerce', 'Para contratos de fotografia contínua'],
    campos: ['Nome e CPF do fotógrafo', 'Nome e CPF/CNPJ do cliente', 'Descrição: tipo de trabalho, data do evento, número de fotos', 'Valor recebido (total ou parcela)', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Fotógrafo pode ser MEI?', a: 'Sim. Fotógrafo pode ser MEI (CNAE 7420-0/01). Como MEI, emite nota fiscal para empresas.' },
      { q: 'Recibo de fotógrafo inclui a licença de uso das fotos?', a: 'Não automaticamente. O recibo comprova o pagamento. A licença de uso (quem pode usar as fotos, para quê, por quanto tempo) deve ser detalhada no contrato.' },
      { q: 'Fotógrafo pode cobrar sinal?', a: 'Sim. É prática comum cobrar 30-50% de sinal ao fechar o contrato. Emita um recibo de sinal e outro ao finalizar a entrega das fotos.' },
    ],
    related: ['designer', 'freelancer', 'consultor'],
  },
  {
    slug: 'medico',
    name: 'Médico',
    prepoLabel: 'para Médico',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Médico',
    keyword: 'recibo para medico',
    metaDescription: 'Modelo gratuito de recibo para médico pessoa física. Para consultas particulares, laudos e pareceres. Gere em PDF sem cadastro.',
    intro: 'Médicos que atendem de forma particular precisam emitir recibo por consultas, laudos e procedimentos. O documento serve também para reembolso em planos de saúde.',
    quando: ['Por consultas particulares', 'Para laudos e pareceres médicos', 'Por procedimentos realizados fora de clínica', 'Quando o paciente solicita para reembolso'],
    campos: ['Nome, CRM e CPF do médico', 'Nome e CPF do paciente', 'Descrição: tipo de consulta ou procedimento', 'Data do atendimento', 'Valor recebido', 'Assinatura do médico'],
    faqs: [
      { q: 'Recibo médico serve para reembolso do plano de saúde?', a: 'Depende do plano. Muitos planos aceitam recibos de médicos credenciados ou com CRM. Outros exigem nota fiscal. Consulte as regras do seu plano.' },
      { q: 'Médico pessoa física precisa emitir nota fiscal?', a: 'Para consultas particulares a pacientes pessoa física, o recibo com CRM é amplamente aceito. Para serviços a empresas, emita nota fiscal de serviços.' },
      { q: 'Recibo médico pode ser deduzido no imposto de renda?', a: 'Sim. Despesas médicas com recibo podem ser deduzidas integralmente no IRPF, sem limite. O recibo deve conter nome do paciente, CRM do médico e valor pago.' },
    ],
    related: ['autonomo', 'consultor', 'fisioterapeuta'],
  },
  {
    slug: 'advogado',
    name: 'Advogado',
    prepoLabel: 'para Advogado',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Advogado',
    keyword: 'recibo para advogado',
    metaDescription: 'Modelo gratuito de recibo de honorários advocatícios. Para advogados autônomos e escritórios de advocacia. Gere em PDF sem cadastro.',
    intro: 'Advogados que atuam como autônomos ou que recebem honorários de clientes pessoa física devem emitir recibo de honorários advocatícios. O documento cumpre a função de nota fiscal para este tipo de serviço.',
    quando: ['Ao receber honorários iniciais ou de êxito', 'Por consultas e pareceres jurídicos', 'Para contratos de assessoria mensal', 'Por audiências ou diligências avulsas'],
    campos: ['Nome, CPF e OAB do advogado', 'Nome e CPF/CNPJ do cliente', 'Descrição: natureza do serviço jurídico ou processo', 'Honorários recebidos', 'Data do recebimento', 'Assinatura do advogado'],
    faqs: [
      { q: 'Recibo de honorários substitui nota fiscal?', a: 'Para serviços a pessoas físicas, o recibo com OAB é amplamente aceito. Para empresas, consulte a OAB do seu estado e a legislação municipal — muitos municípios exigem NFS-e mesmo de advogados autônomos.' },
      { q: 'Honorários advocatícios são dedutíveis do IR?', a: 'Sim, em alguns casos. Honorários pagos em ações judiciais trabalhistas e algumas outras ações podem ser deduzidos no IRPF do cliente. Informe seu cliente sobre isso.' },
      { q: 'Como tratar honorários de êxito no recibo?', a: 'Emita um recibo específico para honorários de êxito, descrevendo: processo, instância, resultado obtido e o percentual ou valor acordado no contrato.' },
    ],
    related: ['consultor', 'autonomo', 'medico'],
  },
  {
    slug: 'arquiteto',
    name: 'Arquiteto',
    prepoLabel: 'para Arquiteto',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Arquiteto',
    keyword: 'recibo para arquiteto',
    metaDescription: 'Modelo gratuito de recibo para arquiteto autônomo. Para projetos, laudos e consultorias de arquitetura. Gere em PDF sem cadastro.',
    intro: 'Arquitetos autônomos que desenvolvem projetos para pessoas físicas precisam emitir recibo por honorários de projetos e consultorias. O documento formaliza a relação profissional.',
    quando: ['Ao receber por projeto arquitetônico', 'Para laudos e pareceres técnicos', 'Por consultoria de decoração ou interiores', 'Para contratos de acompanhamento de obra'],
    campos: ['Nome, CPF e CAU/CREA do arquiteto', 'Nome e CPF/CNPJ do cliente', 'Descrição: tipo de projeto, endereço da obra', 'Honorários recebidos (parcela ou total)', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Arquiteto precisa de ART no recibo?', a: 'A ART (Anotação de Responsabilidade Técnica) é um documento separado obrigatório para projetos. O recibo é o comprovante de pagamento dos honorários.' },
      { q: 'Arquiteto autônomo pode emitir nota fiscal?', a: 'Arquitetos podem abrir MEI para projetos de menor escala. Para projetos maiores, abrir uma empresa (Simples Nacional) permite emitir nota fiscal com alíquota menor.' },
      { q: 'Como parcelar honorários de arquitetura?', a: 'É comum parcelar em etapas do projeto: sinal na contratação, pagamento na entrega de anteprojeto e pagamento final na entrega do projeto executivo. Emita recibo em cada parcela.' },
    ],
    related: ['consultor', 'engenheiro', 'autonomo'],
  },
  {
    slug: 'engenheiro',
    name: 'Engenheiro',
    prepoLabel: 'para Engenheiro',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Engenheiro',
    keyword: 'recibo para engenheiro',
    metaDescription: 'Modelo gratuito de recibo para engenheiro autônomo. Para projetos, laudos, consultorias e ART. Gere em PDF sem cadastro.',
    intro: 'Engenheiros autônomos que prestam serviços técnicos para pessoas físicas devem emitir recibo de honorários. O documento registra o pagamento por projetos, laudos e consultorias.',
    quando: ['Ao receber por projeto de engenharia', 'Para laudos técnicos e perícias', 'Por consultoria ou assessoria técnica', 'Para serviços de gerenciamento de obra'],
    campos: ['Nome, CPF e CREA do engenheiro', 'Nome e CPF/CNPJ do cliente', 'Descrição: tipo de serviço técnico', 'Valor dos honorários', 'Data do recebimento', 'Assinatura do engenheiro'],
    faqs: [
      { q: 'Engenheiro pode ser MEI?', a: 'Engenharia NÃO está na lista de atividades permitidas para MEI. Engenheiros autônomos devem abrir empresa (MEI não é possível) ou trabalhar como autônomos com RPA/recibo.' },
      { q: 'Recibo de engenheiro serve como comprovante de ART?', a: 'Não. A ART é emitida no CREA. O recibo comprova o pagamento dos honorários. São documentos diferentes.' },
      { q: 'Como cobrar laudos de engenharia?', a: 'Laudos podem ser cobrados por hora técnica ou valor fixo por laudo. Documente no recibo o tipo de laudo, endereço do imóvel e finalidade.' },
    ],
    related: ['arquiteto', 'consultor', 'autonomo'],
  },
  {
    slug: 'nutricionista',
    name: 'Nutricionista',
    prepoLabel: 'para Nutricionista',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Nutricionista',
    keyword: 'recibo para nutricionista',
    metaDescription: 'Modelo gratuito de recibo para nutricionista. Para consultas de nutrição, planos alimentares e assessoria esportiva. Gere em PDF sem cadastro.',
    intro: 'Nutricionistas autônomos que atendem pacientes de forma particular devem emitir recibo por consultas e elaboração de planos alimentares. O documento pode ser usado para reembolso.',
    quando: ['Por consulta nutricional particular', 'Para planos alimentares e acompanhamento', 'Por consultoria em empresas ou academias', 'Para assessoria nutricional esportiva'],
    campos: ['Nome, CRN e CPF do nutricionista', 'Nome e CPF do paciente', 'Descrição: tipo de atendimento', 'Valor recebido', 'Data do atendimento', 'Assinatura'],
    faqs: [
      { q: 'Recibo de nutricionista é dedutível do IR?', a: 'Nutricionistas não constam no rol de profissionais cujos serviços são dedutíveis no IR (limitado a médicos e dentistas). Verifique com seu contador caso haja atualização legal.' },
      { q: 'Nutricionista pode ser MEI?', a: 'Não. Nutricionistas são profissionais de saúde regulamentados pelo CRN e não podem ser MEI. Atuam como autônomos (CPF) ou abrem empresa (CNPJ).' },
      { q: 'Como formalizar atendimentos online de nutrição?', a: 'Para atendimentos telepresenciais, o recibo deve descrever "consulta nutricional online" com a data da sessão. O documento tem a mesma validade do atendimento presencial.' },
    ],
    related: ['medico', 'fisioterapeuta', 'personal-trainer'],
  },
  {
    slug: 'fisioterapeuta',
    name: 'Fisioterapeuta',
    prepoLabel: 'para Fisioterapeuta',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Fisioterapeuta',
    keyword: 'recibo para fisioterapeuta',
    metaDescription: 'Modelo gratuito de recibo para fisioterapeuta. Para sessões de fisioterapia particular e atendimento domiciliar. Gere em PDF sem cadastro.',
    intro: 'Fisioterapeutas autônomos que realizam sessões particulares ou atendimento domiciliar devem emitir recibo por cada sessão ou pacote de atendimentos. O documento facilita reembolsos e comprovação de renda.',
    quando: ['Por sessão de fisioterapia particular', 'Para pacotes de sessões (por semana ou mês)', 'Por atendimento domiciliar', 'Para reabilitação pós-cirúrgica particular'],
    campos: ['Nome, CREFITO e CPF do fisioterapeuta', 'Nome e CPF do paciente', 'Descrição: número e tipo de sessões', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Recibo de fisioterapia pode ser reembolsado pelo plano?', a: 'Depende do plano e da cobertura. Planos com cobertura ambulatorial podem reembolsar sessões com fisioterapeuta credenciado. Emita o recibo com CREFITO para facilitar.' },
      { q: 'Fisioterapeuta pode ser MEI?', a: 'Não. Fisioterapeutas são profissionais de saúde regulamentados e não podem ser MEI.' },
      { q: 'Como cobrar sessões domiciliares de fisioterapia?', a: 'Sessões domiciliares geralmente têm valor adicional pela deslocamento. Inclua no recibo se a taxa de deslocamento está incluída ou discriminada separadamente.' },
    ],
    related: ['medico', 'nutricionista', 'personal-trainer'],
  },
  {
    slug: 'personal-trainer',
    name: 'Personal Trainer',
    prepoLabel: 'para Personal Trainer',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Personal Trainer',
    keyword: 'recibo para personal trainer',
    metaDescription: 'Modelo gratuito de recibo para personal trainer. Para treinos presenciais, online e consultoria de exercícios. Gere em PDF sem cadastro.',
    intro: 'Personal trainers autônomos devem emitir recibo para cada pagamento por sessão de treino ou mensalidade. O documento formaliza o serviço e serve como comprovante de renda.',
    quando: ['Por sessão avulsa de personal', 'Para mensalidade de treino', 'Por consultoria e elaboração de treino online', 'Para treinos coletivos ou semi-presenciais'],
    campos: ['Nome, CREF e CPF do personal trainer', 'Nome e CPF do aluno/cliente', 'Descrição: número de sessões ou período', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Personal trainer pode ser MEI?', a: 'Personal Trainer (Instrutor de Academia - CNAE 9313-1/00) está na lista MEI. Como MEI, pode emitir nota fiscal para academias e empresas.' },
      { q: 'Como cobrar personal trainer por mensalidade?', a: 'Defina o pacote (ex: 3x por semana = 12 sessões/mês). Emita um único recibo mensal com o total pago e o número de sessões.' },
      { q: 'Recibo de personal trainer serve para dedução no IR?', a: 'Não. Gastos com personal trainer não são dedutíveis no IRPF (apenas despesas médicas em sentido estrito são dedutíveis).' },
    ],
    related: ['fisioterapeuta', 'nutricionista', 'autonomo'],
  },
  {
    slug: 'manicure',
    name: 'Manicure',
    prepoLabel: 'para Manicure',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Manicure',
    keyword: 'recibo para manicure',
    metaDescription: 'Modelo gratuito de recibo para manicure autônoma. Para serviços de manicure e pedicure a domicílio ou salão. Gere em PDF sem cadastro.',
    intro: 'Manicures autônomas que atendem a domicílio ou em salão podem emitir recibo para clientes que precisam de comprovante de pagamento. O documento facilita comprovação de renda.',
    quando: ['Por atendimento a domicílio', 'Para clientes que precisam de comprovante', 'Para formalizar serviços em salão parceiro', 'Para declarar renda no IRPF'],
    campos: ['Nome e CPF da manicure', 'Nome do cliente', 'Descrição: serviços realizados', 'Valor recebido', 'Data do atendimento', 'Assinatura'],
    faqs: [
      { q: 'Manicure pode ser MEI?', a: 'Sim. Manicure e Pedicure (CNAE 9602-5/02) está na lista MEI. Como MEI, a manicure tem CNPJ, pode emitir nota fiscal e tem acesso a benefícios como aposentadoria pelo INSS.' },
      { q: 'Manicure precisa emitir nota fiscal para clientes?', a: 'Como MEI, a emissão de NFS-e é obrigatória para serviços a empresas. Para clientes pessoa física, o recibo simples é suficiente.' },
      { q: 'Como comprovar renda como manicure autônoma?', a: 'Acumule recibos mensais e extrato bancário. Para financiamentos, 3-6 meses de comprovantes são suficientes para a maioria das instituições.' },
    ],
    related: ['diarista', 'autonomo', 'faxineiro'],
  },
  {
    slug: 'cozinheiro',
    name: 'Cozinheiro',
    prepoLabel: 'para Cozinheiro',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Cozinheiro',
    keyword: 'recibo para cozinheiro',
    metaDescription: 'Modelo gratuito de recibo para cozinheiro autônomo. Para serviços de buffet, eventos e gastronomia. Gere em PDF sem cadastro.',
    intro: 'Cozinheiros e chefs autônomos que prestam serviços para eventos ou refeições particulares precisam emitir recibo ao ser pagos. O documento registra o serviço prestado.',
    quando: ['Por serviço de buffet em evento', 'Para refeições em casa (chef à domicílio)', 'Por marmitex e quentinhas para empresas', 'Para aulas de culinária particulares'],
    campos: ['Nome e CPF do cozinheiro', 'Nome e CPF/CNPJ do contratante', 'Descrição: tipo de serviço, número de pessoas, cardápio', 'Valor recebido', 'Data do evento/serviço', 'Assinatura'],
    faqs: [
      { q: 'Cozinheiro pode ser MEI?', a: 'Sim. Cozinheiro pode ser MEI (Cozinheiro - CNAE 5620-1/02). Como MEI, emite nota fiscal e tem acesso a benefícios do INSS.' },
      { q: 'Recibo de buffet deve detalhar o cardápio?', a: 'É recomendado incluir uma descrição resumida do serviço (ex: "buffet para 50 pessoas — coquetel de encerramento"). Não precisa listar cada item do cardápio.' },
      { q: 'Como cobrar serviços de chef à domicílio?', a: 'Cobrar por pessoa (serviço de mesa) ou por hora é comum. Inclua no recibo o que está e o que não está incluso (ingredientes, deslocamento, equipamentos).' },
    ],
    related: ['autonomo', 'freelancer', 'diarista'],
  },
  {
    slug: 'contador',
    name: 'Contador',
    prepoLabel: 'para Contador',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Contador',
    keyword: 'recibo para contador',
    metaDescription: 'Modelo gratuito de recibo de honorários para contador autônomo. Para serviços de contabilidade, IRPF e consultoria fiscal. Gere em PDF.',
    intro: 'Contadores autônomos que prestam serviços para pessoas físicas devem emitir recibo de honorários. Para serviços a empresas, a nota fiscal é obrigatória.',
    quando: ['Por declaração de IRPF individual', 'Para consultoria e planejamento tributário', 'Por serviços de abertura de empresa', 'Para revisão de balancetes avulsos'],
    campos: ['Nome, CRC e CPF do contador', 'Nome e CPF do cliente', 'Descrição: tipo de serviço contábil', 'Honorários recebidos', 'Data do recebimento', 'Assinatura do contador'],
    faqs: [
      { q: 'Contador pode emitir recibo para pessoa física?', a: 'Sim. Para clientes pessoa física, o recibo com CRC é suficiente. Para empresas, emita nota fiscal de serviços.' },
      { q: 'Honorários de contador são dedutíveis do IR?', a: 'Honorários pagos a contador para elaboração de declaração de IRPF podem ser dedutíveis. Consulte as regras vigentes da Receita Federal.' },
      { q: 'Contador MEI pode fazer contabilidade para empresas?', a: 'Contadores não podem ser MEI (profissão regulamentada). Atuam como autônomos (CPF) ou abrem empresa contábil (CNPJ).' },
    ],
    related: ['consultor', 'advogado', 'autonomo'],
  },
  {
    slug: 'cuidador-de-idosos',
    name: 'Cuidador de Idosos',
    prepoLabel: 'para Cuidador de Idosos',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Cuidador de Idosos',
    keyword: 'recibo para cuidador de idosos',
    metaDescription: 'Modelo gratuito de recibo para cuidador de idosos. Para serviços de cuidado, acompanhamento e auxílio em domicílio. Gere em PDF.',
    intro: 'Cuidadores de idosos autônomos devem emitir recibo por seus serviços. O documento formaliza o pagamento e ajuda na comprovação de renda.',
    quando: ['Por diária ou mensalidade de cuidado', 'Para acompanhamento em consultas e exames', 'Por plantão noturno ou fim de semana', 'Para famílias que precisam de comprovante para declaração'],
    campos: ['Nome e CPF do cuidador', 'Nome e CPF do familiar responsável', 'Nome do idoso assistido', 'Descrição: tipo de cuidado e período', 'Valor recebido', 'Assinatura'],
    faqs: [
      { q: 'Cuidador de idosos precisa de carteira assinada?', a: 'Cuidadores que trabalham mais de 2 dias por semana para a mesma família devem ter carteira assinada (emprego doméstico). Para trabalhos avulsos ou menos de 2 dias/semana, é autônomo.' },
      { q: 'Gastos com cuidador de idoso são dedutíveis do IR?', a: 'Não diretamente. Porém, se o cuidador for contratado formalmente (eSocial Doméstico), o INSS pago pelo empregador pode ser deduzido no IRPF.' },
      { q: 'Como comprovante de renda para financiamento como cuidador?', a: 'Acumule recibos mensais (pelo menos 3-6 meses) e extratos bancários mostrando os créditos. Bancos digitais costumam aceitar essa documentação.' },
    ],
    related: ['diarista', 'baba', 'autonomo'],
  },
  {
    slug: 'baba',
    name: 'Babá',
    prepoLabel: 'para Babá',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Babá',
    keyword: 'recibo para baba',
    metaDescription: 'Modelo gratuito de recibo para babá autônoma. Para cuidados com crianças por diária ou mensalidade. Gere em PDF sem cadastro.',
    intro: 'Babás autônomas que trabalham em poucas casas ou de forma avulsa precisam de recibo para comprovar pagamentos e renda. O documento também ajuda as famílias na organização financeira.',
    quando: ['Por diária de babá', 'Para mensalidade fixa de babá frequente', 'Por fim de semana ou feriado trabalhado', 'Quando a família pede comprovante para imposto'],
    campos: ['Nome e CPF da babá', 'Nome e CPF do responsável pela criança', 'Período trabalhado (dias ou horas)', 'Valor recebido', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Babá que trabalha todo dia precisa de carteira assinada?', a: 'Sim. Babá que trabalha 3 ou mais dias por semana para a mesma família é empregada doméstica e precisa ter carteira assinada e ser registrada no eSocial Doméstico.' },
      { q: 'Babá pode ser MEI?', a: 'Babá não está na lista de atividades MEI. Como autônoma (menos de 3 dias/semana), emite recibo simples.' },
      { q: 'Gastos com babá são dedutíveis do IR?', a: 'Não diretamente. Se a babá for empregada doméstica formal, o INSS patronal pode ser deduzido no limite legal do IRPF.' },
    ],
    related: ['diarista', 'cuidador-de-idosos', 'autonomo'],
  },
  {
    slug: 'faxineiro',
    name: 'Faxineiro',
    prepoLabel: 'para Faxineiro',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Faxineiro',
    keyword: 'recibo para faxineiro',
    metaDescription: 'Modelo gratuito de recibo para faxineiro autônomo. Para limpeza residencial e comercial. Gere em PDF sem cadastro.',
    intro: 'Faxineiros autônomos que realizam limpezas avulsas ou mensais podem emitir recibo ao receber. O documento comprova o serviço e o pagamento.',
    quando: ['Por faxina avulsa', 'Para clientes mensais', 'Por limpeza pós-obra ou pós-mudança', 'Quando o contratante pede comprovante'],
    campos: ['Nome e CPF do faxineiro', 'Nome e CPF do contratante', 'Descrição: tipo de limpeza e local', 'Valor recebido', 'Data do serviço', 'Assinatura'],
    faqs: [
      { q: 'Faxineiro pode ser MEI?', a: 'Sim. Serviço de Limpeza (CNAE 8121-4/00) está na lista MEI. Como MEI, o faxineiro pode emitir nota fiscal para empresas e ter CNPJ.' },
      { q: 'Qual a diferença entre faxineiro e diarista?', a: 'Na prática, são termos usados como sinônimos. Juridicamente, o vínculo empregatício (carteira assinada) depende da frequência e do vínculo, não do título.' },
      { q: 'Faxineiro precisa pagar imposto sobre o recibo?', a: 'Como autônomo, deve declarar rendimentos no IRPF. Como MEI, paga uma contribuição mensal fixa (DAS) e está isento de IR sobre os rendimentos do MEI.' },
    ],
    related: ['diarista', 'autonomo', 'manicure'],
  },
  {
    slug: 'jardineiro',
    name: 'Jardineiro',
    prepoLabel: 'para Jardineiro',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Jardineiro',
    keyword: 'recibo para jardineiro',
    metaDescription: 'Modelo gratuito de recibo para jardineiro autônomo. Para manutenção de jardins e paisagismo. Gere em PDF sem cadastro.',
    intro: 'Jardineiros autônomos que prestam serviços de manutenção ou paisagismo devem emitir recibo ao ser pagos. O documento formaliza o serviço e protege ambas as partes.',
    quando: ['Por manutenção periódica de jardim', 'Após serviço de paisagismo', 'Por poda e limpeza avulsa', 'Para instalação de jardim vertical ou horta'],
    campos: ['Nome e CPF do jardineiro', 'Nome e CPF do contratante', 'Descrição: tipo de serviço e endereço', 'Valor recebido', 'Data do serviço', 'Assinatura'],
    faqs: [
      { q: 'Jardineiro pode ser MEI?', a: 'Sim. Jardineiro (CNAE 0161-0/03) está na lista MEI.' },
      { q: 'Como cobrar manutenção de jardim: por visita ou por mês?', a: 'Mensalidade é mais comum para jardins de manutenção regular. Defina o número de visitas mensais incluídas e emita um recibo mensal.' },
      { q: 'Jardineiro deve incluir materiais no recibo?', a: 'Sim, se cobra pelos materiais junto (terra, adubo, plantas). Discrimine "mão de obra" e "materiais" para maior transparência.' },
    ],
    related: ['pedreiro', 'autonomo', 'faxineiro'],
  },
  {
    slug: 'mecanico',
    name: 'Mecânico',
    prepoLabel: 'para Mecânico',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Mecânico',
    keyword: 'recibo para mecanico',
    metaDescription: 'Modelo gratuito de recibo para mecânico autônomo. Para serviços de reparo automotivo e manutenção de veículos. Gere em PDF.',
    intro: 'Mecânicos autônomos que realizam serviços fora de uma oficina registrada devem emitir recibo ao ser pagos. O documento detalha o serviço realizado e os valores cobrados.',
    quando: ['Por serviço de mecânica geral', 'Para trocar óleo e filtros fora de oficina', 'Por serviços elétricos automotivos', 'Para reparos emergenciais ou a domicílio'],
    campos: ['Nome e CPF do mecânico', 'Nome e CPF do cliente', 'Descrição: serviço realizado, modelo e placa do veículo', 'Valor da mão de obra (separado das peças)', 'Data do serviço', 'Assinatura'],
    faqs: [
      { q: 'Recibo de mecânico deve incluir peças trocadas?', a: 'Recomendado. Liste as peças usadas com os valores separados da mão de obra. Isso protege o mecânico e o cliente em caso de garantia ou reclamação.' },
      { q: 'Mecânico autônomo pode ser MEI?', a: 'Sim. Mecânico de veículos automotores (CNAE 4520-0/01) está na lista MEI.' },
      { q: 'Garantia de serviço de mecânico: como registrar?', a: 'Inclua no recibo ou contrato o prazo de garantia do serviço (ex: "3 meses de garantia para a troca de freios"). Isso é obrigação do Código de Defesa do Consumidor (CDC).' },
    ],
    related: ['eletricista', 'autonomo', 'consultor'],
  },
  {
    slug: 'costureira',
    name: 'Costureira',
    prepoLabel: 'para Costureira',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Costureira',
    keyword: 'recibo para costureira',
    metaDescription: 'Modelo gratuito de recibo para costureira autônoma. Para ajustes, costura sob medida e produção de peças. Gere em PDF sem cadastro.',
    intro: 'Costureiras autônomas podem emitir recibo por serviços de ajuste, costura sob medida ou produção de peças. O documento comprova o pagamento e o serviço entregue.',
    quando: ['Por ajuste ou conserto de peça de roupa', 'Para vestidos de festa ou noiva sob medida', 'Por produção de uniformes ou peças em série', 'Para serviços de bordado ou customização'],
    campos: ['Nome e CPF da costureira', 'Nome e CPF do cliente', 'Descrição: peça(s) e serviço realizado', 'Valor recebido', 'Data da entrega e do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Costureira pode ser MEI?', a: 'Sim. Costureira (Alfaiate/Costureiro de vestuário - CNAE 1412-6/01) pode ser MEI.' },
      { q: 'Como cobrar peças sob medida?', a: 'Cobre metade no momento do pedido (como sinal) e o restante na entrega. Emita recibo de sinal e recibo final separados.' },
      { q: 'Prazo de entrega deve constar no recibo?', a: 'O recibo comprova o pagamento. Para registrar o prazo acordado, use um contrato simples ou inclua uma nota descritiva no recibo.' },
    ],
    related: ['autonomo', 'freelancer', 'diarista'],
  },
  {
    slug: 'tecnico-em-ti',
    name: 'Técnico em TI',
    prepoLabel: 'para Técnico em TI',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Técnico em TI',
    keyword: 'recibo para tecnico em ti',
    metaDescription: 'Modelo gratuito de recibo para técnico em TI. Para suporte, manutenção de computadores e redes. Gere em PDF sem cadastro.',
    intro: 'Técnicos em informática autônomos que prestam suporte técnico, manutenção de equipamentos ou gerenciam redes devem emitir recibo por cada serviço ou contrato.',
    quando: ['Por serviço de suporte técnico avulso', 'Para manutenção de computadores e notebooks', 'Por configuração de redes e infraestrutura', 'Para contratos de suporte mensal (SLA)'],
    campos: ['Nome e CPF do técnico', 'Nome e CPF/CNPJ do cliente', 'Descrição: serviço realizado, equipamento ou sistema', 'Valor recebido', 'Data do atendimento', 'Assinatura'],
    faqs: [
      { q: 'Técnico em TI pode ser MEI?', a: 'Suporte técnico em TI (CNAE 6209-1/00) está na lista MEI. Como MEI, o técnico pode emitir nota fiscal para empresas.' },
      { q: 'Como cobrar suporte técnico por hora ou por chamado?', a: 'Por chamado é mais simples para o cliente (valor fixo por visita). Por hora é justo para serviços complexos. Defina antes e inclua no recibo.' },
      { q: 'Garantia de serviço de TI: quantos dias?', a: 'O Código de Defesa do Consumidor garante 90 dias de garantia para serviços. Inclua no recibo ou contrato o prazo de garantia e o que cobre.' },
    ],
    related: ['programador', 'consultor', 'autonomo'],
  },
  {
    slug: 'garcom',
    name: 'Garçom',
    prepoLabel: 'para Garçom',
    toolHref: '/ferramentas/recibo-simples',
    toolLabel: 'Gerar Recibo para Garçom',
    keyword: 'recibo para garcom',
    metaDescription: 'Modelo gratuito de recibo para garçom autônomo. Para eventos, festas e contratações avulsas. Gere em PDF sem cadastro.',
    intro: 'Garçons autônomos contratados para eventos, festas corporativas ou particulares precisam emitir recibo ao ser pagos. O documento formaliza a prestação de serviços de garçom.',
    quando: ['Por evento ou festa particular', 'Para buffet corporativo', 'Por serviço em casamento ou formatura', 'Para contratos de garçom avulso em restaurante'],
    campos: ['Nome e CPF do garçom', 'Nome e CPF/CNPJ do contratante', 'Descrição: evento, data e duração do serviço', 'Valor recebido (inclui gorjeta?)', 'Data do recebimento', 'Assinatura'],
    faqs: [
      { q: 'Gorjeta entra no recibo de garçom?', a: 'Gorjeta é facultativa e geralmente não consta no recibo formal. Se acordada previamente como parte do pagamento, pode ser incluída como "taxa de serviço".' },
      { q: 'Garçom pode ser MEI?', a: 'Garçom (Maître/Chefe de salão) pode estar na lista MEI dependendo do CNAE. Consulte o Portal do Empreendedor para confirmar a atividade exata.' },
      { q: 'Contrato de garçom avulso: precisa assinar?', a: 'Para eventos importantes, um contrato simples com escopo, horário e valor protege ambas as partes. O recibo comprova o pagamento posterior.' },
    ],
    related: ['autonomo', 'cozinheiro', 'freelancer'],
  },
]

export const PROFISSOES: Record<string, Profissao> = Object.fromEntries(
  profissoes.map((p) => [p.slug, p]),
)

export const ALL_PROFISSAO_SLUGS = profissoes.map((p) => p.slug)
